# Configuration for Fighter-Net training
dataset_path: '/path/to/aircraft_dataset'  # Path to the dataset
transform:
  - 'Resize': 
      height: 256
      width: 256
  - 'ToTensor': {}  # Convert image to tensor
  - 'Normalize': 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]  # Normalization values for pre-trained models

# Hyperparameters for model
backbone:
  type: 'HybridCNNTransformer'  # Model backbone configuration
  model_size: 'medium'  # 'small', 'medium', or 'large'
  
# Optimizer settings
optimizer:
  type: 'Adam'  # Optimizer type
  learning_rate: 0.001
  weight_decay: 1e-5

# Training settings
training:
  epochs: 50  # Number of training epochs
  batch_size: 32  # Batch size for training
  lr_scheduler: 'StepLR'  # Learning rate scheduler
  lr_step_size: 10  # Step size for learning rate scheduler
  lr_gamma: 0.1  # Gamma for learning rate scheduler
  checkpoint_dir: './trained_models'  # Directory to save model checkpoints
  
  
  
 #dataset_path: Specifies the path to the dataset.
#transform: Preprocessing steps, such as resizing and normalizing images.
#backbone: Configuration for the backbone network, including the type and number of layers.
#optimizer: Optimizer settings such as type, learning rate, and weight decay.
#training: Training settings, including the number of epochs, batch size, and learning rate scheduler.

